name: Build and Push Container Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Get short SHA
        id: slug
        run: echo "SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)" >> "$GITHUB_OUTPUT"

      - name: Build and push container image
        run: |
          # Build the image
          podman build -t ghcr.io/${{ github.repository }}/virtual-thermostat:latest \
                       -t ghcr.io/${{ github.repository }}/virtual-thermostat:${{ github.sha }} \
                       -t ghcr.io/${{ github.repository }}/virtual-thermostat:${{ steps.slug.outputs.SHORT_SHA }} \
                       -f ./virtual-thermostat.dockerfile .

          # Push all tags
          podman push ghcr.io/${{ github.repository }}/virtual-thermostat:latest
          podman push ghcr.io/${{ github.repository }}/virtual-thermostat:${{ github.sha }}
          podman push ghcr.io/${{ github.repository }}/virtual-thermostat:${{ steps.slug.outputs.SHORT_SHA }}
