name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
          pip install -e .

      - name: Check formatting with Black
        run: black --check --diff virtual_thermostat

      - name: Lint with flake8
        run: flake8 virtual_thermostat

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install actionlint
        run: |
          # Download and install actionlint
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          echo "${PWD}" >> "$GITHUB_PATH"

      - name: Run actionlint
        run: actionlint

  smoke-test:
    name: Smoke Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    needs: [lint, actionlint]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    container:
      image: python:${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e '.[dev]'

      - name: Run smoke tests
        run: |
          pytest tests/test_smoke.py -v

  build-and-push:
    needs: [smoke-test, lint, actionlint]
    permissions:
      contents: read
      packages: write
    if: github.ref == 'refs/heads/master'

    strategy:
      fail-fast: false
      matrix:
        include:
           - base-img: "ubuntu-latest"
           - base-img: "ubuntu-24.04-arm"
           - base-img: "self-hosted"
             target_arch: "armv6l"
             arch_params: --build-arg=TARGETARCH=arm --platform=linux/arm/v6
             flavor: "-sensor"

    runs-on: ${{ matrix.base-img }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Podman
        if: ${{ matrix.base-img != 'self-hosted' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Get short SHA
        id: slug
        run: echo "SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)" >> "$GITHUB_OUTPUT"

      - name: Build and push container image
        run: |
          ARCH="${{ matrix.target_arch }}"
          [ -z "${ARCH}" ] && ARCH="$(uname -m)"
          # Build the image
          podman build ${{ matrix.arch_params }} -t "ghcr.io/${{ github.repository }}/virtual-thermostat${{ matrix.flavor }}-${ARCH}:latest" \
                       -t "ghcr.io/${{ github.repository }}/virtual-thermostat${{ matrix.flavor }}-${ARCH}:${{ github.sha }}" \
                       -t "ghcr.io/${{ github.repository }}/virtual-thermostat${{ matrix.flavor }}-${ARCH}:${{ steps.slug.outputs.SHORT_SHA }}" \
                       -f ./virtual-thermostat${{ matrix.flavor }}.dockerfile .

          # Push all tags
          podman push "ghcr.io/${{ github.repository }}/virtual-thermostat${{ matrix.flavor }}-${ARCH}:latest"
          podman push "ghcr.io/${{ github.repository }}/virtual-thermostat${{ matrix.flavor }}-${ARCH}:${{ github.sha }}"
          podman push "ghcr.io/${{ github.repository }}/virtual-thermostat${{ matrix.flavor }}-${ARCH}:${{ steps.slug.outputs.SHORT_SHA }}"
