name: Lint and Format

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
          pip install -e .

      - name: Check formatting with Black
        run: black --check --diff virtual_thermostat

      - name: Lint with flake8
        run: flake8 virtual_thermostat

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run actionlint
        uses: actionlint/actionlint-action@v1
        with:
          # Optionally use a specific version of actionlint
          version: "1.6.24"
