name: Tests

on:
  push:
  pull_request:

jobs:
  smoke-test:
    name: Smoke Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    container:
      image: python:${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Run smoke tests
        run: |
          pytest tests/test_smoke.py -v
